calculate_regression:
  name: Calculate Regression
  description: Calculate linear regression for a room
  fields:
    room_name:
      name: Room Name
      description: Name of the room to calculate regression for
      required: true
      selector:
        text:

clear_samples:
  name: Clear Samples
  description: Clear all samples for a room
  fields:
    room_name:
      name: Room Name
      description: Name of the room to clear samples for
      required: true
      selector:
        text:

add_sample:
  name: Add Sample
  description: Manually add a brightness/lux sample
  fields:
    room_name:
      name: Room Name
      description: Name of the room
      required: true
      selector:
        text:
    brightness:
      name: Brightness
      description: Brightness value (0-255)
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 1
    lux:
      name: Lux
      description: Lux value
      required: true
      selector:
        number:
          min: 0
          max: 10000
          step: 0.1

adaptive_learning:
  name: Adaptive Learning
  description: Run adaptive learning to improve the model
  fields:
    room_name:
      name: Room Name
      description: Name of the room
      required: true
      selector:
        text:

calculate_target_brightness:
  name: Calculate Target Brightness
  description: Calculate optimal brightness for desired lux level
  fields:
    room_name:
      name: Room Name
      description: Name of the room
      required: true
      selector:
        text:
    target_lux:
      name: Target Lux
      description: Desired lux level
      required: true
      selector:
        number:
          min: 1
          max: 2000
          step: 1
    current_brightness:
      name: Current Brightness
      description: Current brightness (for fallback calculation)
      required: false
      default: 255
      selector:
        number:
          min: 1
          max: 255
          step: 1 

force_light_refresh:
  name: Force Light Entity Refresh
  description: Force Home Assistant to refresh light entity states using homeassistant.update_entity service.
  fields:
    room_name:
      name: Room Name
      description: Name of the room to force refresh.
      required: true
      selector:
        text: